import * as XLSX from "xlsx";

// Raw data: LAB_NAME | CATEGORY | TEST_NAME | PRICE
const raw = `CENTER FOR MOLECULAR SCIENCE AND GENETIC STUDIES | MOLECULAR BIOLOGY | Wound Swab gene xpert | 4000
LABORATORY | HISTOPATHOLOGICAL | HISTOPATHOLOGY [BREAST BIG] | 35000
LABORATORY | HAEMATOLOGY/SEROLOGY | 24-hour Urinary Free Cortisole X3 | 176000
LABORATORY | MOLECULAR BIOLOGY | Logistic for DNA sample collection (deceased) - Outside Owerri | 150000
RADIOLOGY | DIGITAL X-RAY | CARITAS (ADULT) | 8000
ULTRA SOUND | ULTRASOUND | FIBRO SCAN | 40000
OPD PACKAGE | OPD PACKAGE | PHYSICAL EXAM (ABROAD) | 10000
OPD PACKAGE | OPD PACKAGE | COLLINS SCHOOL PACKAGE | 12000
RADIOLOGY | DIGITAL X-RAY | COLONOSCOPY | 220000
CT SCAN | CT SCAN | ABDOMINAL PELVIC CT | 200000
LABORATORY | HAEMATOLOGY/SEROLOGY | 24HRS URINE VMA | 123500
LABORATORY | HAEMATOLOGY/SEROLOGY | IMMUNOHISTOCHEMISTRY 4 PANELS | 140000
HISTOPATHOLOGY | HISTOPATHOLOGICAL | Progesterone receptor | 25000
HISTOPATHOLOGY | HISTOPATHOLOGICAL | P16 | 25000
HISTOPATHOLOGY | HISTOPATHOLOGICAL | P53 | 25000
HISTOPATHOLOGY | HISTOPATHOLOGICAL | Estrogen receptor | 25000
ULTRA SOUND | ULTRASOUND | OBSTETRICS BPP | 30000
LABORATORY | HAEMATOLOGY/SEROLOGY | BP READING | 1000
OPD PACKAGE | OPD PACKAGE | DACA PRE-M (FEMALE) | 15000
OPD PACKAGE | OPD PACKAGE | DACA PRE-M (MALE) | 13000
OPD PACKAGE | OPD PACKAGE | E/U/CR PROFILE | 18000
OPD PACKAGE | OPD PACKAGE | KFT PROFILE | 18000
RADIOLOGY | DIGITAL X-RAY | C-XRAY (CARITAS CHILD) | 8000
LABORATORY | HISTOPATHOLOGICAL | IMMUNOHISTOCHEMISTRY 6 PANELS | 150000
OPD PACKAGE | OPD PACKAGE | HCG PROFILE | 22000
OPD PACKAGE | OPD PACKAGE | BROAD OAK STAFF | 14400
OPD PACKAGE | OPD PACKAGE | COMPLETE METABOLIC PANEL | 54300
OTHERS | ADMINISTRATION | LOGISTICS / HOME SERVICE | 40000
LABORATORY | SPECIAL INVESTIGATION | 17-OH PROGESTERONE | 80000
OPD PACKAGE | OPD PACKAGE | TRINITY COLLEGE | 27500
LABORATORY | MICROBIOLOGY/PARASITOLOGY | BREAST DISCHARGE M/C/S | 15000
LABORATORY | CHEMISTRY | ASPIRATE CHEM & FBC | 15000
LABORATORY | MICROBIOLOGY/PARASITOLOGY | THROAT SWAB (MANUAL) | 15000
OPD PACKAGE | OPD PACKAGE | NMDPR COMPREHENSIVE FEMALE BELOW 40 | 123600
OPD PACKAGE | OPD PACKAGE | NMDPR COMPREHENSIVE MALE BELOW 40 | 123600
OPD PACKAGE | OPD PACKAGE | NMDPR COMPREHENSIVE FEMALE ABOVE 40 | 260600
OPD PACKAGE | OPD PACKAGE | NMDPR COMPREHENSIVE MALE ABOVE 40 | 246600
LABORATORY | MICROBIOLOGY/PARASITOLOGY | SPUTUM M/C/S (MANUAL) | 10000
LABORATORY | MICROBIOLOGY/PARASITOLOGY | NASAL SWAB M/C/S (MANUAL) | 15000
RADIOLOGY | DIGITAL X-RAY | RAD. IVU FILM REPRINT | 5000
LABORATORY | HAEMATOLOGY/SEROLOGY | LAB RESULT REPRINT | 4500
RADIOLOGY | DIGITAL X-RAY | ECG GRAPH REPRINT | 2000
LABORATORY | MOLECULAR BIOLOGY | STD PACKAGE | 200000
LABORATORY | CHEMISTRY | BONE PROFILE | 150000
LABORATORY | MICROBIOLOGY/PARASITOLOGY | EYE SWAB M/C/S MANUAL | 15000
LABORATORY | MICROBIOLOGY/PARASITOLOGY | ABSCESS M/C/S AUTO | 30000
RADIOLOGY | DIGITAL X-RAY | CARITAS CHEST XRAY (0-15YRS) | 8000
LABORATORY | MOLECULAR BIOLOGY | LOGISTICS FOR DECEASED SAMPLING | 55000
LABORATORY | MICROBIOLOGY/PARASITOLOGY | URINE M/C/S MANUAL | 13500
ULTRA SOUND | ULTRASOUND | OCULAR SCAN | 12000
LABORATORY | SINGLE HORMONE TESTS | TACROLIMUS LEVEL | 60000
LABORATORY | HAEMATOLOGY/SEROLOGY | CBC | 9500
LABORATORY | CHEMISTRY | FLP | 18000
LABORATORY | MICROBIOLOGY/PARASITOLOGY | ASPIRATE M/C/S MANUAL | 15000
LABORATORY | HISTOPATHOLOGICAL | HISTOLOGY (BIG ABDOMAYOMA) | 55000
RADIOLOGY | DIGITAL X-RAY | MAMMOGRAM ONLY | 25500
LABORATORY | HAEMATOLOGY/SEROLOGY | TBLAMP | 4000
LABORATORY | MICROBIOLOGY/PARASITOLOGY | WOUND M/C/S (MANUAL) | 15000
LABORATORY | MICROBIOLOGY/PARASITOLOGY | URETHRAL SWAB M/C/S (MANUAL) | 15000
RADIOLOGY | DIGITAL X-RAY | RCUG | 40000
LABORATORY | MICROBIOLOGY/PARASITOLOGY | PUS M/C/S MANUAL | 15000
LABORATORY | MICROBIOLOGY/PARASITOLOGY | ENDOCERVICAL SWAB (MANUAL) | 15000
LABORATORY | MICROBIOLOGY/PARASITOLOGY | EAR SWAB M/C/S (MANUAL) | 15000
LABORATORY | MICROBIOLOGY/PARASITOLOGY | HVS M/C/S (MANUAL) | 15000
LABORATORY | MICROBIOLOGY/PARASITOLOGY | BLOOD CULTURE M/C/S (MANUAL) | 20000
LABORATORY | MICROBIOLOGY/PARASITOLOGY | SFA M/C/S (MANUAL) | 20000
LABORATORY | MOLECULAR BIOLOGY | URINE SODIUM ESTIMATE | 55000
LABORATORY | MICROBIOLOGY/PARASITOLOGY | TB LAMP | 2000
LABORATORY | SPECIAL INVESTIGATION | ACETIC FLUID CYTOLOGY | 30000
LABORATORY | SPECIAL INVESTIGATION | COVID TEST | 42000
LABORATORY | SPECIAL INVESTIGATION | INTERLEUKIN-6 | 200000
LABORATORY | SPECIAL INVESTIGATION | PROCALCITONIN | 147200
LABORATORY | SPECIAL INVESTIGATION | ALDOSTERONE | 90000
LABORATORY | SPECIAL INVESTIGATION | RUBELLA IgG / IgM | 100000
LABORATORY | SPECIAL INVESTIGATION | IgE (IMMUNOGLOBULIN E) | 55000
LABORATORY | SPECIAL INVESTIGATION | ENA PANEL | 150000
LABORATORY | HAEMATOLOGY/SEROLOGY | MP AUTO PLUS WIDAL | 5500
LABORATORY | SEROLOGY | MP AUTO | 5000
LABORATORY | MICROBIOLOGY/PARASITOLOGY | NAIL CLIPPING KOH CULTURE | 9500
OPD PACKAGE | OPD PACKAGE | ARRIVE ALIVE FEMALE BELOW 40YRS | 33500
LABORATORY | MICROBIOLOGY/PARASITOLOGY | STOOL ANALYSIS | 4500
LABORATORY | SPECIAL INVESTIGATION | HEV ANTIBODY IGM | 45000
LABORATORY | SPECIAL INVESTIGATION | HDV ANTIBODY IGM | 55000
LABORATORY | SPECIAL INVESTIGATION | HBC ANTIBODY IGM | 25000
LABORATORY | SPECIAL INVESTIGATION | HAV ANTIBODY IGM | 25000
OPD PACKAGE | OPD PACKAGE | MARRIAGE (FEMALE) | 6000
OPD PACKAGE | OPD PACKAGE | MARRIAGE (MALE) | 5000`;

const rows = raw.trim().split("\n").map(line => {
  const parts = line.split("|").map(p => p.trim());
  // parts[0] = lab/dept, parts[1] = category, parts[2] = name, parts[3] = price
  return {
    name: parts[2] || "",
    description: "",
    base_price: Number(parts[3]) || 0,
    category: parts[1] || "General",
    code: "",
    is_active: true,
    lab_specific_price: "",
  };
});

const ws = XLSX.utils.json_to_sheet(rows);
const wb = XLSX.utils.book_new();
XLSX.utils.book_append_sheet(wb, ws, "Investigations");
XLSX.writeFile(wb, "investigations_bulk_upload.xlsx");

console.log(`✅ Generated investigations_bulk_upload.xlsx with ${rows.length} rows.`);
